#!/usr/bin/env python

import sys
from rqt_speech_status.rqt_speech_status import SpeechStatusPlugin
from rqt_gui.main import Main

plugin = 'rqt_speech_status'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
